name: run web automated tests in lambda-test

on:
  workflow_dispatch:
    inputs:
      test-tags-to-include:
        description: 'smoke or regression'
        required: false
        default: 'smoke'
        type: choice
        options:
          - 'smoke'
          - 'regression'
      environment:
        description: 'staging or dev'
        required: false
        default: 'staging'
        type: choice
        options:
          - 'dev'
          - 'staging'

jobs:
  web-tests-in-lambda-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: execute-web-tests
        run: |
          mvn clean test -Dgroups="${{ inputs.test-tags-to-include }} & web" -Denvironment=${{ inputs.environment }} -Dselenide.browser=com.tmb.provider.web.remote.LambdaTestChromeProvider -DlambdaTestUserName=${{ secrets.LAMBDA_TEST_USER_NAME }} -DlambdaTestAccessKey=${{ secrets.LAMBDA_TEST_ACCESS_KEY }}

      - uses: vimtor/action-zip@v1
        timeout-minutes: 30
        if: always()
        with:
          files: ./target/allure-results/
          dest: ./allure-results.zip

      - uses: actions/upload-artifact@v3
        timeout-minutes: 30
        if: always()
        with:
          name: allure-results
          path: ./allure-results.zip