name: run mobile automated tests in lambda-test cloud

on:
  workflow_dispatch:
    inputs:
      test-tags-to-include:
        description: 'smoke or regression'
        required: false
        default: 'smoke'
        type: choice
        options:
          - 'smoke'
          - 'regression'
      environment:
        description: 'staging or dev'
        required: false
        default: 'staging'
        type: choice
        options:
          - 'dev'
          - 'staging'

jobs:
  mobile-tests-in-lambda-test-cloud:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: run android tests
        run: | 
          mvn clean test -Dselenide.browser=com.tmb.provider.mobile.remote.LambdaTestAndroidAppProvider -Dgroups="${{ inputs.test-tags-to-include }} & mobile" -Denvironment=${{ inputs.environment }} -DlambdaTestUserName=${{ secrets.LAMBDA_TEST_USER_NAME }} -DlambdaTestAccessKey=${{ secrets.LAMBDA_TEST_ACCESS_KEY }} -DlambdaTestAppUrl=${{ secrets.LAMBDA_TEST_APP_URL }}

      - uses: vimtor/action-zip@v1
        if: always()
        with:
          files: ./target/allure-results/
          dest: ./allure-results.zip

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: ./allure-results.zip