name: run api automated tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test-tags-to-include:
        description: 'smoke or regression'
        required: false
        default: 'smoke'
        type: choice
        options:
          - 'smoke'
          - 'regression'
      environment:
        description: 'staging or dev'
        required: false
        default: 'staging'
        type: choice
        options:
          - 'dev'
          - 'staging'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        timeout-minutes: 30
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: execute-api-tests-workflow-dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          mvn clean test -Dgroups="${{ inputs.test-tags-to-include }} & api" -Denvironment=${{ inputs.environment }}

      - name: execute-api-tests-pull-request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mvn clean test -Dgroups=api -Denvironment=staging

      - uses: vimtor/action-zip@v1
        timeout-minutes: 30
        if: always()
        with:
          files: ./target/allure-results/
          dest: ./allure-results.zip

      - uses: actions/upload-artifact@v4
        timeout-minutes: 30
        if: always()
        with:
          name: allure-results
          path: ./allure-results.zip
